export default [
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 1,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
  {
    trace_id: 'xxx',
    timestamp: 0,
    user_id: 'hello',
    deck_id: 'yyy',
    deck_name: 'big demon hunter',
    result: 0,
    hero_id: 'demon_hunter',
    opponent_hero_id: 'mage',
  },
];
